name: terra_reports
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^10.2.14
  firebase_database: ^9.0.12
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

